### ISSUE TITLE
Latex4CorеlDraw

### ISSUE THREAD

**Issue by NikolaMutavdic** [InteractiveComputerGraphics/Latex4CorelDRAW#10]
Dear Mr. Bender,

I am trying to use your LaTex plugin for Corel Draw, and it created docker Latex with all of it's buttons.

But, unfortunately,  when I enter formula in Create latex object dialog box, and press Ok, I get the following error message:

Unhandled expectation has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.

Object reference not set to an instance of an object. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Latex4CorelDraw.LatexDialog.generateEquation(Boolean createShape) in C:\Program Files\Corel\CorelDRAW Graphics Suite 2021\Programs64\Addons\Latex4CorelDRAW-master\LatexDialog.cs:line 250
   at Latex4CorelDraw.LatexDialog.buttonOk_Click(Object sender, EventArgs e) in C:\Program Files\Corel\CorelDRAW Graphics Suite 2021\Programs64\Addons\Latex4CorelDRAW-master\LatexDialog.cs:line 195
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

and so on...
I am using CorelDRAW Graphics Suite 2021, and I installed Visual Studio Enterprise Edition 2022, in order to activate docker.

Can You please hep me with this issue?

Sincerely,
Nikola

**Comment by janbender** [comment]
Did you set the path to latex.exe correctly in the options?

**Comment by NikolaMutavdic** [comment]
Thank you for your quick response!

The answer to your question is yes. I am using texlive 2021, and I previously set the path to latex.exe correctly. (C:\texlive\2021\bin\win32)

**Comment by NikolaMutavdic** [comment]
Dear Mr. Bender,

I installed texlive2023 and  set path to new latex.exe file and it seams that the problem is now fixed. Hope that I will not get error messages in the future.

Thank you for your assistance!

With kind regards,
Nikola
